import Main from "./components/main/index";
import Undangan from "./components/undangan/index"
import Head from "next/head";
import Akad from "./components/akad";
import Gallery from "./components/gallery";
import Video from "./components/video";
import Amplop from "./components/amplop";
import Einvitation from "./components/einvitation";
import Nama from "./components/nama";
import Pesan from "./components/pesan";
import Footer from "./components/footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="index-background">
        <Main />
        <Nama />
        <Undangan />
        <Akad />
      </div>
      <Gallery />
      <div className="free-space" />
      <Video />
      <Amplop />
      <Pesan />
      {/* belum dipakai sekarang
      <Einvitation /> */}
      <Footer />
    </div>
  );
}
